name: Create GitHub Release and Publish Package

on:
  release:
    types:
      - published

permissions:
  contents: write
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Update permissions for gradlew
        run: chmod +x ./gradlew

      - name: Set repository URL environment variable
        run: |
          REPO_NAME=${GITHUB_REPOSITORY#*/}
          echo "ORG_GRADLE_PROJECT_githubPackagesRegistryURL=https://maven.pkg.github.com/${{ github.repository_owner }}/$REPO_NAME" >> $GITHUB_ENV

      - name: Build artifacts and publish to GitHub Packages
        env:
          GPR_USER: github-actions
          GPR_KEY: ${{ secrets.CALYPSONET_PACKAGES_TOKEN }}
          ORG_GRADLE_PROJECT_githubPackagesRegistryUsername: ${{ github.actor }}
          ORG_GRADLE_PROJECT_githubPackagesRegistryPassword: ${{ secrets.PACKAGE_PUBLICATION_TOKEN }}
          ORG_GRADLE_PROJECT_releaseTag: ${{ github.event.release.tag_name }}
        run: ./gradlew build :plugin:publish

      - name: (Optional) Collect artifacts for release page
        run: |
          mkdir -p release-artifacts
          cp plugin-mock/build/outputs/aar/*-release-mock.aar release-artifacts/ || true

      - name: (Optional) Upload artifacts to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: release-artifacts/*
          token: ${{ secrets.GITHUB_TOKEN }}
